services:
  caddy:
    image: caddy:2.11.3@sha256:ec18ee54aab3315c22e25f3b2babda73ff8007d39b13b3bd1bfffa2f0444c7d9
    container_name: remnawave-caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./selfsteal:/srv/selfsteal:ro
      - ./certs:/etc/caddy/certs:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
      - /dev/shm:/dev/shm

  cover-web:
    image: vectorim/element-web:v1.12.18@sha256:c21772a1eabeededa19be591343f548995e458ec34ba8f27425ae923c10af82e
    container_name: remnawave-cover-element
    restart: unless-stopped
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - ./element-web/config.json:/app/config.json:ro

  remnanode:
    image: remnawave/node:2.8.0@sha256:03f14935751b4ab565181e2b1766ccd1a9ac349d6839acd3ee49014e543fa232
    container_name: remnanode
    hostname: remnanode
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      NODE_PORT: "2222"
      SECRET_KEY: "${SECRET_KEY}"
      CUSTOM_CORE_URL: "${CUSTOM_CORE_URL:-}"
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./certs/privkey.key:/etc/nginx/certs/privkey.key:ro
      - /dev/shm:/dev/shm
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
